---
- name: Config Web VM with Docker
  hosts: elkservers
  become: true
  tasks:
  - name: Increase memory
    command: sysctl -w vm.max_map_count=524288
  - name: docker.io
    apt:
      force_apt_get: yes
      name: docker.io
      state: present

  - name: Install pip
    apt:
      force_apt_get: yes
      name: python-pip
      state: present

  - name: Install Docker python module
    pip:
      name: docker
      state: present

  - name: download and launch a docker web container
    docker_container:
      name: elk
      image: sebp/elk
      state: started
      ports:
      - 5601:5601
      - 9200:9200
      - 5044:5044